# -*- coding: utf-8 -*-
"""Beginner python project Calculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQ_TfFquRJ77d8vDTN6ja2qDpvc-099z
"""

import math

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    return "Error: Division by zero" if b == 0 else a / b

def power(a, b):
    return a ** b

def square_root(a):
    return "Error: Negative number" if a < 0 else math.sqrt(a)

def factorial(n):
    return "Error: Negative number" if n < 0 else math.factorial(n)

def nPr(n, r):
    if r > n or n < 0 or r < 0:
        return "Error: Invalid n or r"
    return math.perm(n, r)

def nCr(n, r):
    if r > n or n < 0 or r < 0:
        return "Error: Invalid n or r"
    return math.comb(n, r)

def dec_to_bin(n):
    return bin(n)[2:]

def dec_to_hex(n):
    return hex(n)[2:].upper()

def bin_to_dec(b):
    try:
        return int(b, 2)
    except:
        return "Error: Invalid binary number"

def hex_to_dec(h):
    try:
        return int(h, 16)
    except:
        return "Error: Invalid hexadecimal number"

def main_menu():
    print("\n--- Welcome To Advanced Calculator ---")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Power")
    print("6. Square Root")
    print("7. Factorial")
    print("8. nPr")
    print("9. nCr")
    print("10. Decimal to Binary")
    print("11. Decimal to Hexadecimal")
    print("12. Binary to Decimal")
    print("13. Hexadecimal to Decimal")
    print("0. Exit")

def calculator():
    while True:
        main_menu()
        choice = input("Choose an option (0-13): ")

        if choice == "0":
            print("Goodbye!")
            break

        elif choice in ["1", "2", "3", "4", "5"]:
            a = float(input("Enter first number: "))
            b = float(input("Enter second number: "))
            if choice == "1":
                print("Result:", add(a, b))
            elif choice == "2":
                print("Result:", subtract(a, b))
            elif choice == "3":
                print("Result:", multiply(a, b))
            elif choice == "4":
                print("Result:", divide(a, b))
            elif choice == "5":
                print("Result:", power(a, b))

        elif choice == "6":
            a = float(input("Enter number: "))
            print("Result:", square_root(a))

        elif choice == "7":
            n = int(input("Enter number: "))
            print("Result:", factorial(n))

        elif choice == "8":
            n = int(input("Enter n: "))
            r = int(input("Enter r: "))
            print("Result:", nPr(n, r))

        elif choice == "9":
            n = int(input("Enter n: "))
            r = int(input("Enter r: "))
            print("Result:", nCr(n, r))

        elif choice == "10":
            n = int(input("Enter decimal number: "))
            print("Binary:", dec_to_bin(n))

        elif choice == "11":
            n = int(input("Enter decimal number: "))
            print("Hexadecimal:", dec_to_hex(n))

        elif choice == "12":
            b = input("Enter binary number: ")
            print("Decimal:", bin_to_dec(b))

        elif choice == "13":
            h = input("Enter hexadecimal number: ")
            print("Decimal:", hex_to_dec(h))

        else:
            print("Invalid option. Please try again.")


calculator()